// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiKozGsi5w0ftbHYUL6E7L39Tv7_t2wvQ',
    appId: '1:672646882187:web:fdc0178e7a7c68ae3f058e',
    messagingSenderId: '672646882187',
    projectId: 'cgpa-calculator-8e6ae',
    authDomain: 'cgpa-calculator-8e6ae.firebaseapp.com',
    storageBucket: 'cgpa-calculator-8e6ae.firebasestorage.app',
    measurementId: 'G-RXTDPCVBGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7yzE7Xkl6IusQeRJ7QevWZJmskMT2_NI',
    appId: '1:672646882187:android:ff6cf4d02fd80e663f058e',
    messagingSenderId: '672646882187',
    projectId: 'cgpa-calculator-8e6ae',
    storageBucket: 'cgpa-calculator-8e6ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_jSxbZInpQI9suWq2TIV7i2kNm4SrXN4',
    appId: '1:672646882187:ios:d1b8acc532a675313f058e',
    messagingSenderId: '672646882187',
    projectId: 'cgpa-calculator-8e6ae',
    storageBucket: 'cgpa-calculator-8e6ae.firebasestorage.app',
    iosBundleId: 'com.example.cgpaCalculatorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_jSxbZInpQI9suWq2TIV7i2kNm4SrXN4',
    appId: '1:672646882187:ios:d1b8acc532a675313f058e',
    messagingSenderId: '672646882187',
    projectId: 'cgpa-calculator-8e6ae',
    storageBucket: 'cgpa-calculator-8e6ae.firebasestorage.app',
    iosBundleId: 'com.example.cgpaCalculatorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiKozGsi5w0ftbHYUL6E7L39Tv7_t2wvQ',
    appId: '1:672646882187:web:2d945309a468a3f03f058e',
    messagingSenderId: '672646882187',
    projectId: 'cgpa-calculator-8e6ae',
    authDomain: 'cgpa-calculator-8e6ae.firebaseapp.com',
    storageBucket: 'cgpa-calculator-8e6ae.firebasestorage.app',
    measurementId: 'G-JW8WDTENNB',
  );
}
